version: 2

jobs:
  build:
    machine: true

    steps:
      - checkout
      
      - run: |
          mkdir /home/circleci/logs

      - run: |
          docker run -e GO111MODULE=on \
            -v /home/circleci/project:/go/src/github.com/giantswarm/e2ekindprototype \
            --workdir /go/src/github.com/giantswarm/e2ekindprototype \
            quay.io/giantswarm/golang:1.11.3 \
            go build -o e2ekindprototype .

      - run: |
          sudo /home/circleci/project/e2ekindprototype

      - store_artifacts:
          path: /home/circleci/logs
          destination: logs
