version: 2

jobs:
  build:
    machine: true

    steps:
      - checkout

      - run: |
          docker run quay.io/giantswarm/golang:1.11.3 \
            -e GO111MODULE=on \
            -v /home/circleci/project:/go/src/github.com/giantswarm/e2ekindprototype \
            --workdir /go/src/github.com/giantswarm/e2ekindprototype \
            go build -o e2ekindprototype .

      - run: |
          ./project/e2ekindprototype
